// export const memberList = [
//   { name: "陈中伟", email: "chenzhongwei01@corp.netease.com" },
//   { name: "许泽豪", email: "xuzehao01@corp.netease.com" },
//   { name: "熊宇", email: "xiongyu@corp.netease.com" },
//   { name: "李晶晶", email: "lijingjing@corp.netease.com" },
//   { name: "李美婷", email: "limeiting@corp.netease.com" },
//   { name: "佘晓彤", email: "shexiaotong@corp.netease.com" },
//   { name: "刘健红", email: "liujianhong02@corp.netease.com" },
//   { name: "初晓悦", email: "cxyn0693@corp.netease.com" },
//   { name: "陈振辉", email: "chenzhenhui@corp.netease.com" },
//   { name: "袁智娇", email: "yuanzhijiao@corp.netease.com" },
//   { name: "吴永豪", email: "wuyonghao01@corp.netease.com" },
//   { name: "陈家麟", email: "chenjialin01@corp.netease.com" },
//   { name: "郭剑飞", email: "gzguojianfei@corp.netease.com" },
//   { name: "毛靓", email: "maoliang@corp.netease.com" },
//   { name: "赵雪纯", email: "gzzhaoxuechun@corp.netease.com" },
//   { name: "黄绮雯", email: "huangqiwen@corp.netease.com" },
//   { name: "曾玉婷", email: "zengyuting@corp.netease.com" },
//   { name: "冯蕴茹", email: "fengyunru@corp.netease.com" },
//   { name: "肖军", email: "xiaojun01@corp.netease.com" },
//   { name: "汪阳紫", email: "wangyangzi@corp.netease.com" },
//   { name: "吴雯婷", email: "wuwenting02@corp.netease.com" },
//   { name: "李锦荣", email: "lijinrong02@corp.netease.com" },
//   { name: "邱桃", email: "elaine@corp.netease.com" },
//   { name: "车蕾", email: "chelei@corp.netease.com" },
//   { name: "陈慧敏", email: "chenhuimin02@corp.netease.com" },
//   { name: "韩栗颖", email: "hanliying@corp.netease.com" },
//   { name: "王彦澍", email: "wangyanshu01@corp.netease.com" },
//   { name: "马琳昆", email: "malinkun@corp.netease.com" },
//   { name: "邹观欣雨", email: "zouguanxinyu@corp.netease.com" },
//   { name: "倪昊明", email: "nihaoming@corp.netease.com" },
//   { name: "刘钰", email: "liuyu38@corp.netease.com" },
//   { name: "谢雨诗", email: "xieyushi@corp.netease.com" },
//   { name: "崔泰红", email: "cuitaihong@corp.netease.com" },
//   { name: "高炘", email: "gaoxin03@corp.netease.com" },
//   { name: "叶茜", email: "yeqian@corp.netease.com" },
//   { name: "周千一", email: "zqyn0721@corp.netease.com" },
//   { name: "范恩颖", email: "gzfanenying@corp.netease.com" },
//   { name: "肖佩雯", email: "gzxiaopeiwen@corp.netease.com" },
//   { name: "徐亚萍", email: "xypn0719@corp.netease.com" },
//   { name: "翟冰清", email: "zhaibingqing@corp.netease.com" },
//   { name: "康博", email: "bokang@corp.netease.com" },
//   { name: "江金津", email: "hzjiangjj@corp.netease.com" },
//   { name: "赵穗", email: "zhaosui@corp.netease.com" },
//   { name: "廖晓川", email: "wb.liaoxiaochuan@mesg.corp.netease.com" },
//   { name: "许绵虹", email: "wb.xumianhong@mesg.corp.netease.com" },
//   { name: "赵成男", email: "wb.zhaochengnan@mesg.corp.netease.com" },
//   { name: "高俊丽", email: "wb.gaojunli@mesg.corp.netease.com" },
//   { name: "熊炜琪", email: "wb.xiongweiqi@mesg.corp.netease.com" },
//   { name: "林诗耕", email: "wb.linshigeng01@mesg.corp.netease.com" },
//   { name: "李尚鹏", email: "wb.lishangpeng@mesg.corp.netease.com" },
//   { name: "叶庭瑜", email: "wb.quyu1510@mesg.corp.netease.com" },
//   { name: "黄志隆", email: "wb.huangzhilong@mesg.corp.netease.com" },
//   { name: "黄泳琳", email: "wb.huangyonglin@mesg.corp.netease.com" },
//   { name: "秦丹妮", email: "wb.qindanni@mesg.corp.netease.com" },
//   { name: "李俊威", email: "wb.lijunwei02@mesg.corp.netease.com" },
//   { name: "李子阳", email: "wb.liziyang01@mesg.corp.netease.com" },
//   { name: "李文", email: "wb.liwen12@mesg.corp.netease.com" },
//   { name: "黄子恒", email: "wb.huangziheng@mesg.corp.netease.com" },
//   { name: "周衍衍", email: "wb.zhouyanyan01@mesg.corp.netease.com" },
//   { name: "方碧玲", email: "wb.fangbiling@mesg.corp.netease.com" },
//   { name: "李婷婷", email: "wb.litingting10@mesg.corp.netease.com" },
//   { name: "黄奉仪", email: "huangfengyi@corp.netease.com", isWb: true },
//   { name: "易嘉怡", email: "wb.yijiayi@mesg.corp.netease.com" },
//   { name: "徐家杰", email: "wb.xujiajie@mesg.corp.netease.com" },
//   { name: "李嘉帆", email: "wb.lijiafan@mesg.corp.netease.com" },
//   { name: "钟健航", email: "wb.zhongjianhang01@mesg.corp.netease.com" },
//   { name: "王镭斌", email: "wb.wangleibin@mesg.corp.netease.com" },
//   { name: "李建斌", email: "wb.lijianbin@mesg.corp.netease.com" },
//   { name: "林汉杰", email: "wb.linhanjie@mesg.corp.netease.com" },
//   { name: "彭珊珊", email: "wb.pengshanshan@mesg.corp.netease.com" },
//   { name: "严国球", email: "wb.yanguoqiu@mesg.corp.netease.com" },
//   { name: "白翠莹", email: "wb.baicuiying@mesg.corp.netease.com" },
//   { name: "刘兴涛", email: "wb.liuxingtao@mesg.corp.netease.com" },
//   { name: "廖丽玉", email: "wb.liaoliyu@mesg.corp.netease.com  " },
//   { name: "游卓华", email: "wb.zhyou@mesg.corp.netease.com" },
//   { name: "秦宇昱", email: "wb.qinyuyu@mesg.corp.netease.com" },
//   { name: "谢丽莹", email: "wb.xieliying@mesg.corp.netease.com" },
//   { name: "黄嘉澎", email: "wb.huangjiapeng@mesg.corp.netease.com" },
//   { name: "游云峰", email: "wb.youyunfeng@mesg.corp.netease.com" },
//   { name: "许志豪", email: "wb.xuzhihao02@mesg.corp.netease.com" },
//   { name: "陈伟藩", email: "wb.quyu675@mesg.corp.netease.com" },
// ];

export const memberList = [
  { name: "一筒" },
  { name: "二筒" },
  { name: "三筒" },
  { name: "四筒" },
  { name: "五筒" },
  { name: "六筒" },
  { name: "七筒" },
  { name: "八筒" },
  { name: "九筒" },
  { name: "一万" },
  { name: "二万" },
  { name: "三万" },
  { name: "四万" },
  { name: "五万" },
  { name: "六万" },
  { name: "七万" },
  { name: "八万" },
  { name: "九万" },
  { name: "一条" },
  { name: "二条" },
  { name: "三条" },
  { name: "四条" },
  { name: "五条" },
  { name: "六条" },
  { name: "七条" },
  { name: "八条" },
  { name: "九条" },
  { name: "东" },
  { name: "南" },
  { name: "西" },
  { name: "北" },
  { name: "中" },
  { name: "發" },
  { name: "白板" },

  { name: "一筒*" },
  { name: "二筒*" },
  { name: "三筒*" },
  { name: "四筒*" },
  { name: "五筒*" },
  { name: "六筒*" },
  { name: "七筒*" },
  { name: "八筒*" },
  { name: "九筒*" },
  { name: "一万*" },
  { name: "二万*" },
  { name: "三万*" },
  { name: "四万*" },
  { name: "五万*" },
  { name: "六万*" },
  { name: "七万*" },
  { name: "八万*" },
  { name: "九万*" },
  { name: "一条*" },
  { name: "二条*" },
  { name: "三条*" },
  { name: "四条*" },
  { name: "五条*" },
  { name: "六条*" },
  { name: "七条*" },
  { name: "八条*" },
  { name: "九条*" },
  { name: "东*" },
  { name: "南*" },
  { name: "西*" },
  { name: "北*" },
  { name: "中*" },
  { name: "發*" },
  { name: "白板*" },
];
